name: macos

on:
  pull_request:
    branches:
    - main
  push:
    branches:
    - main
    - '*-ci'

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ macos-11 ]
        cc: [ clang ]
    steps:
    - uses: actions/checkout@v2
    - name: dependencies
      run: brew install libcbor llvm mandoc pkg-config zlib
    - name: build
      env:
        CC: ${{ matrix.cc }}
      run: ./.actions/build-osx-clang
